function snake_rec = InitABody(n, Snake)
    snake_rec = rectangle( ...
        "FaceColor", [1 1 1], ...
        "EdgeColor", 'none', ...
        'Position', [Snake.Body(n,1)-0.5 Snake.Body(n,2)-0.5 1 1], ...
        "Parent",fig);
end