function [ax, fig] = InitPlayground(onKeyPress)
    GRID_W = 20;
    GRID_H = 20;

    fig = figure('Name', 'Snake', 'NumberTitle', 'off', ...
        'MenuBar', 'none', 'ToolBar', 'none', ...
        'KeyPressFcn', onKeyPress);

    ax = axes('Parent', fig, ...
        'XLim', [-4.5 GRID_W + 0.5], 'YLim', [0.5 GRID_H + 0.5], ...
        'XTick', [], 'YTick', [], ...
        'Color', [0.05 0.05 0.05], ...
        'DataAspectRatio', [1 1 1]);

    hold(ax, 'on');


    rectangle(ax, ...
        'Position', [-4.5, 0.5, 5, 20], ...
        'FaceColor', 'white', ...
        'EdgeColor', 'none');
end
