function LoginFigure()
load('Top.mat', 'Top');
Top(4).Name = "";

fig = figure( ...
    'Name', 'Login', ...
    'NumberTitle', 'off', ...
    'MenuBar', 'none', ...
    'ToolBar', 'none', ...
    'Position', [500 400 300 180]);

uicontrol(fig, ...
    'Style', 'text', ...
    'String', 'Enter your username:', ...
    'Position', [50 120 200 25], ...
    'FontSize', 12);

nameBox = uicontrol(fig, ...
    'Style', 'edit', ...
    'Position', [50 85 200 30], ...
    'FontSize', 12);

uicontrol(fig, ...
    'Style', 'pushbutton', ...
    'String', 'Login', ...
    'Position', [100 35 100 35], ...
    'FontSize', 12, ...
    'Callback', @loginCallback);

uiwait(fig);

    function loginCallback(~, ~)
         Top(4).Name = get(nameBox, 'String');

        if isempty(Top(4).Name)
            errordlg('Username cannot be empty.');
            return;
        end

        if isvalid(fig)
            close(fig);
        end
    end
save('Top.mat', 'Top');
end